name: Deployment

on:
  workflow_dispatch:
    
jobs:
  deploy:
    env:
      BUILD_CONFIG: Release
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: Azure/login@v1.4.3
      with: 
        creds: ${{ secret.AZURE_CREDENTIALS }}
