name: Deployment

on:
  workflow_dispatch:
    
jobs:
  deploy:
    env:
      BUILD_CONFIG: Release
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v3
